### ISSUE TITLE
config.ini file

### ISSUE THREAD

**Issue by guiranierii** [alessandrodd/playstore_crawler#1]
Hello!

Could you send the config.yml file example and the config.ini file that's missing?
I'm not an expert and as a Designer somethings in pythons still very obscure to me.

I would really like to try this project.

Thank you!

**Comment by d4op** [comment]
config.ini got replaced by config.yml I guess.

**Comment by alessandrodd** [comment]
That's correct; I'll fix the documentation to reflect the change.
